### ISSUE TITLE
How about using serviceSubject instead of APP_CELL_ADMIN_INFO

### ISSUE THREAD

**Issue by yoh1496** [personium/app-personium-trails#12]
In `acc_info.js`, we hard-coded the admin password.

https://github.com/personium/app-personium-trails/blob/5c97a33cda16f89e38c71a44c473a8a99d294b21/src/app/auth/acc_info.js

maybe, this occurs some security problem.

how about using serviceSubject instead of APP_CELL_ADMIN_INFO in auth 

https://github.com/personium/app-personium-trails/blob/5c97a33cda16f89e38c71a44c473a8a99d294b21/src/app/auth/personium.js#L25

**Comment by dixonsiu** [comment]
I just find out that the service subject is usable in the following command, too. It will retrieve the box object where the script is in.

    _p.as('serviceSubject').cell().box()
